name: Echo FLAG on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  echo_flag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo FLAG Variable
        env:
          FLAG: ${{ secrets.FLAG }}
        run: echo $FLAG
        
